<ul class="headertextcontainer">
    <li>
        <a href="tel:(020) 482 44 40"><i class="fa fa-phone" aria-hidden="true"></i> (020) 482 44 40</a>
    </li>
    <li>
        <a href="mailto:info@lcomp.nl"><i class="fa fa-envelope" aria-hidden="true"></i> Info@lcomp.nl</a>
    </li>
    <li>
        <a href="http://www.islonline.net/start/ISLLightClient"><i class="fa fa-download" aria-hidden="true"></i> Remote helpdesk</a>
    </li>
</ul>